### ISSUE TITLE
Deprecated 'crypto, npm

### ISSUE THREAD

**Issue by sreejithkummil** [microsoft/BotFramework-DirectLineJS#295]
@stevengum 

in 
![error](https://user-images.githubusercontent.com/49387686/88169576-ce072b80-cc39-11ea-9fbf-cfcc54c4b3fc.jpeg)
my react native project i use,

npm install botframework-directlinejs --save 

to work properly i need crypto npm.. what can i do?

please help.

node : v14.5.0
botframework-directlinejs : ^0.12.0
react : 16.13.1
react-native :  0.63.1

**Comment by munozemilio** [comment]
@ckkashyap could you please take a look at this?

**Comment by EricDahlvang** [comment]
@stevengum would you please provide an update on this.

**Comment by stevengum** [comment]
I'm working on an issue in the JS repo that would address this problem of pulling in `crypto` into directlinejs, the ETA for the fix is R10.

**Comment by carlosscastro** [comment]
ETA -> R11 (November) unless needed earlier. @ckkashyap any date restrictions on your side?

**Comment by Metroidaron** [comment]
Hello, I am the React-Native developer for my company and I am trying to implement the Bot Framework Direct Line JS in our application for an employee chatbot; I was at first running into a "stream" not found when bundling issue, and was able to resolve it with an install and import of "stream"; but now I am seeing this same Crypto bug and I believe my issue is the same as this one... 

Is there a develop build or beta build or git branch (to npm install) so that I can get my hands on a working model to develop with?  Or a solid work around to get this working in a React Native environment?  I followed the steps of a rather nasty shim process that even described itself as a hack (changing lots of npm modules) and broke too many things to fix so I rolled that back...

Any assistance is greatly appreciated 😄 

I'm also not understanding R11?  it looks like your latest release tag is of 12; so I don't think those numbers are associated...?

**Comment by pavolum** [comment]
We are expecting this to be implemented in R11 which means November 11th time frame

**Comment by cwhitten** [comment]
@stevengum I'm moving this to R12

**Comment by stevengum** [comment]
Fixed via https://github.com/microsoft/BotFramework-DirectLineJS/pull/323.

**Comment by stevengum** [comment]
The fix for resolving Node.js dependencies was just released in version [0.14.1](https://www.npmjs.com/package/botframework-directlinejs/v/0.14.1) of `botframework-directlinejs`.
