### ISSUE TITLE
DirectLine NodeJs  - Duplicate Activity from bot

### ISSUE THREAD

**Issue by lfgonzalez10** [microsoft/BotFramework-DirectLineJS#354]
I am consuming the bot from Node JS Direct Line,
I have the problem that I send an activity and the bot responds to me with duplicate activities (each duplicate activity has the same Conversation Id)

USER message 1
BOT message 1
USER message 2
BOT message 2
BOT message 2
USER message 3
BOT message 3
BOT message 3
BOT message 3
....

When is new conversation
directLine = new DirectLine ({
         token:
       });

When there is conversation
  directLine = new DirectLine ({
         token:
         streamUrl: "",
         conversationId: lastMessage.idConversation,
       });

directLine.activity$
    .filter(activity => activity.type === 'message' && activity.from.id === 'IdBot')
    .subscribe(async function (activity) {
...
}

 
What is the problem?
Thank you

**Comment by stevkan** [comment]
It is expected that each duplicate activity would have the same conversation Id since they all ought to be stemming from the same conversation. However, can you verify that the duplicates have the same activity Id (I would be surprised if the activity Ids were different)?

Also, can you include the code, if any, that you have in the `.subscribe()` part of the `activity$` observer?

You can also reference this HTML based sample I created some time ago. It requires running a "token" server for fetching a token. You also need to include your bot's name in the switch statement. Lastly, it only works with a bot that returns text. It is not setup to accept any cards. But, it should give an idea on how you could construct your own Direct Line app and maybe help identify where a possible mistake lives in yours.

[html-directline.zip](https://github.com/microsoft/BotFramework-DirectLineJS/files/7104710/html-directline.zip)

**Comment by stevkan** [comment]
Closing as resolved.
