### ISSUE TITLE
Suggestion: update connection status when connection is lost

### ISSUE THREAD

**Issue by nicksav** [microsoft/BotFramework-DirectLineJS#46]
Trying to test loosing connection 

`    this.directLine.connectionStatus$
    .subscribe(connectionStatus => {
        return this.connectionSource.next(connectionStatus);
    });
`

Strange but it is not getting called when I drop of wifi. Any idea?
Using inside Angular 4

Thanks
Nick

**Comment by billba** [comment]
That code wouldn't do anything useful. What are you trying to accomplish?

**Comment by nicksav** [comment]
@billba I am using DirectLine as underline layer of alerts and communications. (not just bot)
When user opens a portal web page I am making him "online" and he can easily start using chat (bot) etc.
As soon as connection dropped, I want to show that user is offline now and make chat "disabled".

**Comment by billba** [comment]
(Sorry, at first I misread your code)

It's actually pretty hard to know if we've lost the connection. What does that even mean? If you're using a phone then you may gain and lose the connection on a second by second basis. We could probably all agree that it means "unable to connect over an extended period of time" if we could agree on the definition of "extended".

At this time DLJS doesn't offer a state for this. Attempting to send an activity returns an error, but clients can always retry later (as WebChat does). When listening for activities we just keep trying.

It would be interesting to define a heuristic for "offline" and add a new connection status to reflect that, and then switch back to "online" if the connection shows signs of life. But since it's not a real state, just a heuristic, we'd still want to allow you to send activities and keep trying to listen.

Before considering such a thing we'd need unit tests for DLJS, which are currently sorely lacking.

**Comment by justinwilaby** [comment]
I realize this is a very old thread but I cam across this and thought I'd chime in. Of course [there are APIs and Events](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/Online_and_offline_events) that have existed for quite some time that tell you whether you're online or offline. It may be useful in this case at least for users that are implementing this in a browser like @nicksav 

e.g.
```js
window.addEventListener('offline', () => console.log('Aw snap!')
window.addEventListener('online', () => console.log('Yay!');
```

I hope this helps.

**Comment by billba** [comment]
Oh hey that's cool, I didn't know that.

**Comment by compulim** [comment]
We are tracking the resume/end conversation stories at #124.

**Comment by cwhitten** [comment]
See #124 for updates on this workstream
