### ISSUE TITLE
ExpiredToken errors should be thrown when calling postActivity

### ISSUE THREAD

**Issue by harshithkashyap** [Microsoft/BotFramework-DirectLineJS#55]
From the following snippet, the ExpiredToken error is resolved as success.
```javascript
private catchExpiredToken(error: any) {
        return error === errorExpiredToken
        ? Observable.of("retry")
        : Observable.throw(error);
    }
```

I have the following snippet in my code and the catch block is never reached.
```javascript
try {
    const messageId = await this.pivbotService.directLine
        .postActivity({
            from: this.from,
            type: 'message',
            text: message
        })
        .toPromise();
    console.log(messageId);
    // Logs text "retry"
} catch (err) {
    // Never reached
    console.error(err);
}
```

Shouldn't `catchExpiredToken` method throw error in any case?

**Comment by billba** [comment]
Most posting errors are *nonrecoverable* (reposting is not expected to yield different results), and in those cases we throw an error. But if a token is expired a new one can be obtained, and the message can be reposted. So instead of throwing an error here, we mark the message as "retry" so that it can be reposted later. This admittedly an inelegant solution. It's convenient for WebChat, but maybe not so much for other applications.

The way to handle these is to subscribe to `connectionStatus$` and handle `ConnectionStatus.ExpiredToken`.
