### ISSUE TITLE
Post Activity

### ISSUE THREAD

**Issue by Yash-7** [Microsoft/BotFramework-DirectLineJS#57]
Hey guys, I have a code which posts activity to the directlinejs.
`directLine
 .postActivity({
    
    from: { id: 'myUserId', name: 'myUserName' },
    type: 'message',
    text: 'a message for you, Rudy'
}).subscribe(
    id => console.log("Posted activity, assigned ID ", id),
    error => console.log("Error posting activity", error)
);`

Now, can I add something like `newtext:'some new text'` inside postActivity method.

**Comment by billba** [comment]
Since this is a question about functionality and not a bug report of feature request, please ask it on Stack Overflow (with tag `botframework`) so that others can benefit from the answer. If you post a link to your question here I will answer it there.

Please make sure you provide more detail as to what you are trying to achieve.
