### ISSUE TITLE
$activity stream stops after connectionStatus$ emits 'ExpiredToken'.

### ISSUE THREAD

**Issue by roald-di** [Microsoft/BotFramework-DirectLineJS#73]
Hi,
I am trying to handle the ExpiredToken event as detailed here: https://github.com/Microsoft/BotFramework-WebChat/issues/372#issuecomment-334738789.

However after the ExpiredToken event is emitted the $activity stream completes and it is no longer possible to receive any messages.

Looking at the code it seems that the error thrown here https://github.com/Microsoft/BotFramework-DirectLineJS/blob/1f5e00d76018cff27bbeef2d1d5dcbce946420aa/src/directLine.ts#L384 ends up in this catch https://github.com/Microsoft/BotFramework-DirectLineJS/blob/1f5e00d76018cff27bbeef2d1d5dcbce946420aa/src/directLine.ts#L617 wich results in the completion of the polling stream.

When using websockets the stream instead completes with 'Error: expired token'.

**Comment by roald-di** [comment]
Yes, the stream completes.

I did a ```subscribe()``` on activity$ and it fires the complete handler when using polling and it fires the error handler when using web sockets.

You are right that the catch isn't the actual problem.
The problem is that ```checkConnection``` emits an error when the token expires.

When that happens the stream resulting from ```Observable.interval(this.pollingInterval).combineLatest(this.checkConnection())``` will also emit the error, at that point the catch will swallow the error and continue with an empty stream which effectively completes it.
In the case of websockets, where there is no catch, the error will be instead emitted on activity$, also terminating it.

checkConnection works in other places in the code because there it is always re-invoked and a new stream is created, while in the case of activity$ it is only invoked once when running the constructor,
so once it emits an error it can never recover.

This is a very simplified version of the code which I hope will illustrate better what I'm trying to say 😄:

```javascript
    var ConnectionStatus = {
        Online: 2,
        ExpiredToken: 3
    }

    const connectionStatus$ = new Rx.BehaviorSubject(ConnectionStatus.Online);

    checkConnection = () => {
        let obs = connectionStatus$
            .flatMap(connectionStatus => connectionStatus === ConnectionStatus.ExpiredToken ? Rx.Observable.throw(new Error("expired token")) : Rx.Observable.of(null));

        return obs;
    }

    const fakeInterval$ = new Rx.Subject();

    pollingGetActivity$ = fakeInterval$
        .combineLatest(checkConnection())
        .catch(error => Rx.Observable.empty());

    pollingGetActivity$.subscribe(n => console.log(n[0]), error => console.log(error), () => console.log('completed'));

    fakeInterval$.next(1);
    fakeInterval$.next(2);
    connectionStatus$.next(ConnectionStatus.ExpiredToken);
    fakeInterval$.next(3);
    connectionStatus$.next(ConnectionStatus.Online);
    fakeInterval$.next(4);
```

if you run this you should see
```
1
2
complete
```
but no 3 and 4.

**Comment by tomohisaota** [comment]
Any progress on this issue?

I am using websocket directline with token. 
When token expires , I can successfully renew token, but no new message arrives chat window.

I have confirmed that ConnectionStatus goes back to online.
Also, I have confirmed that my server receives messages even after token renewal.
So it seems that incoming messages are dropped somewhere.

**Comment by ejadib** [comment]
I'm facing the same issue. Any progress on this?

**Comment by ejadib** [comment]
@roald-di have you find any workaround for this?

**Comment by compulim** [comment]
Sorry for not watching this issue earlier.

From what I am seeing in the code, when we hit "expired token", we just simply stop and `connectionStatus$` become `ConnectionStatus.ExpiredToken`.

From what I see on the Web Socket path at https://github.com/Microsoft/BotFramework-DirectLineJS/blob/1f5e00d76018cff27bbeef2d1d5dcbce946420aa/src/directLine.ts#L695, we are waiting until the web page reconnect with a new token.

On the REST polling path at https://github.com/Microsoft/BotFramework-DirectLineJS/blob/1f5e00d76018cff27bbeef2d1d5dcbce946420aa/src/directLine.ts#L604, we are stopped with `ConnectionStatus.ExpiredToken`.

I didn't try out the real code yet and maybe I overlooked at something, I guess the behavior is correct right now.

Is it because the `activity$` is not re-subscribed, thus, the `reconnect` doesn't work as expected?

Could you guys tell me more about your expectations on the expired token reconnect story?

**Comment by ckkashyap** [comment]
@roald-di - thanks for your sample. I looked at this issue and looks like to me that in the catch block, we create a new empty Observable which ends up producing the "complete". We are looking into this to figure out what would be a good way to fix this issue so that consumers of activity$ can resume after a token expiry.

**Comment by ckkashyap** [comment]
Please take a look at https://github.com/Microsoft/BotFramework-DirectLineJS/blob/ckk/workaroundthe403issue/src/directLine.ts - to work around this problem.

**Comment by compulim** [comment]
This issue is fixed.
